Implementation of the iteration 2
Josue-Zenteno/ISOFT2-2021-A01 pull request #29
Opened 2020-12-03 12:30 UTC by Josue-Zenteno

Implementation of the iteration 2 has been completed

2020-12-03 16:09 UTC, Carlos-Bernalte approved these changes

2020-12-04 17:39 UTC, luissanty2 approved these changes

2020-12-04 19:41 UTC, jtaraque requested changes
There are some requirements from the Requirements stage that are not properly implemented:
"statistic on average preparation time so that the table is free" and 
"statistic on average time of delivery of the note". 

Aswell as the ones related with codes: 
"order must have a set of codes"
"codes must have an order".

2020-12-05 09:46 UTC, Josue-Zenteno commented
> There are some requirements from the Requirements stage that are not properly implemented:
> "statistic on average preparation time so that the table is free" and
> "statistic on average time of delivery of the note".
> 
> Aswell as the ones related with codes:
> "order must have a set of codes"
> "codes must have an order".

We have taken into account your advices and we have improved the code to achieve the corresponding goals in a more proper way. We will write all the design decisions taken in the Wiki.

2020-12-05 14:25 UTC, jtaraque approved these changes
All good, nice work!

2020-12-07 15:41 UTC, merged